VacationPy

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from config import g_key

Store Part I results into DataFrame

In [6]:
# Load in cities csv
cities_data = pd.read_csv("output_data/cities.csv")
cities_data

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Atuona,-9.80,-139.03,26.03,75,21,6.87,PF,1608506082
1,Hilo,19.73,-155.09,27.00,74,75,2.10,US,1608505835
2,Palmer,42.16,-72.33,0.00,100,90,2.36,US,1608506083
3,Ushuaia,-54.80,-68.30,11.00,49,40,13.40,AR,1608505952
4,Vaini,-21.20,-175.20,29.00,79,20,7.20,TO,1608506084
...,...,...,...,...,...,...,...,...,...
565,Praia da Vitória,38.73,-27.07,18.33,100,75,13.81,PT,1608506142
566,Isangel,-19.55,169.27,29.00,74,40,2.60,VU,1608506142
567,Kerman,30.28,57.08,0.00,67,0,0.34,IR,1608506143
568,Udachny,66.42,112.40,-37.00,65,0,2.00,RU,1608506143
569,Buraidah,26.33,43.98,14.00,87,0,4.10,SA,1608506143

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure